# Generated by Django 5.2 on 2025-07-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='documento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='documento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
