# Generated by Django 5.2 on 2025-08-28 23:41

import django.db.models.deletion
import servicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_clientes_cep_alter_clientes_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=100)),
                ('data_entrada', models.DateField()),
                ('data_prazo', models.DateField()),
                ('status', models.CharField(choices=[('aguardando servico', 'Aguardando Serviço'), ('em andamento', 'Em Andamento'), ('secagem', 'Secagem'), ('polimento', 'Polimento'), ('vistoria', 'Vistoria'), ('finalizado', 'Finalizado'), ('entregue', 'Entregue')], max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20)),
                ('descricao', models.TextField()),
                ('material_adicional', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quem_recebeu', models.CharField(max_length=100)),
                ('aprovacao', models.BooleanField(default=False)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('quem_retirou', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='clientes.clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='ServicosFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=servicos.models.upload_to)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='servicos.servicos')),
            ],
        ),
    ]
