# Generated by Django 5.2 on 2025-07-19 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_status'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='clientes.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='status',
            field=models.CharField(choices=[('aguardando servico', 'Aguardando Serviço'), ('em andamento', 'Em Andamento'), ('manutencao', 'Manutenção'), ('lixa', 'Lixa'), ('pintura', 'Pintura'), ('montagem)', 'Montagem'), ('vistoria', 'Vistoria'), ('finalizado', 'Finalizado'), ('entregue', 'Entregue')], max_length=20),
        ),
    ]
