# Generated by Django 5.2 on 2025-08-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servicos_cliente_alter_servicos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='status',
            field=models.CharField(choices=[('aguardando servico', 'Aguardando Serviço'), ('em andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('entregue', 'Entregue')], max_length=20),
        ),
    ]
