# Generated by Django 5.2 on 2025-09-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servicos_cliente_alter_servicos_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='servicosfotos',
            options={'verbose_name': 'Foto do Serviço', 'verbose_name_plural': 'Fotos dos Serviços'},
        ),
    ]
