# Generated by Django 5.2 on 2025-04-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado')], default='Em andamento', max_length=12)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
