# Generated by Django 5.2 on 2025-07-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='status',
            field=models.CharField(choices=[('em aberto', 'Em Aberto'), ('Finalizado', 'Finalizado')], default='Em andamento', max_length=12),
        ),
    ]
